// <auto-generated />
using System;
using AML.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AML.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AmlDbContext))]
    partial class AmlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AML.Core.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("AML.Core.Entities.ClientService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IntentKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "IntentKey")
                        .IsUnique();

                    b.ToTable("ClientServices", (string)null);
                });

            modelBuilder.Entity("AML.Core.Entities.ServiceAuth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKeyHeaderName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AuthType")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EncryptedApiKey")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EncryptedClientId")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EncryptedClientSecret")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EncryptedPassword")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EncryptedUsername")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Scope")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TokenUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ClientServiceId")
                        .IsUnique();

                    b.ToTable("ServiceAuths", (string)null);
                });

            modelBuilder.Entity("AML.Core.Entities.ServiceEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HttpMethod")
                        .HasColumnType("int");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ClientServiceId")
                        .IsUnique();

                    b.ToTable("ServiceEndpoints", (string)null);
                });

            modelBuilder.Entity("AML.Core.Entities.ServiceFieldMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("SourceField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClientServiceId", "SourceField", "TargetField")
                        .IsUnique();

                    b.ToTable("ServiceFieldMappings", (string)null);
                });

            modelBuilder.Entity("AML.Core.Entities.ServiceHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HeaderKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HeaderValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClientServiceId", "HeaderKey")
                        .IsUnique();

                    b.ToTable("ServiceHeaders", (string)null);
                });

            modelBuilder.Entity("AML.Core.Entities.ServiceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RequestPayload")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponsePayload")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClientServiceId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("RequestedAtUtc");

                    b.ToTable("ServiceLogs", (string)null);
                });

            modelBuilder.Entity("AML.Core.Entities.ClientService", b =>
                {
                    b.HasOne("AML.Core.Entities.Client", "Client")
                        .WithMany("Services")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AML.Core.Entities.ServiceAuth", b =>
                {
                    b.HasOne("AML.Core.Entities.ClientService", "ClientService")
                        .WithOne("Auth")
                        .HasForeignKey("AML.Core.Entities.ServiceAuth", "ClientServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientService");
                });

            modelBuilder.Entity("AML.Core.Entities.ServiceEndpoint", b =>
                {
                    b.HasOne("AML.Core.Entities.ClientService", "ClientService")
                        .WithOne("Endpoint")
                        .HasForeignKey("AML.Core.Entities.ServiceEndpoint", "ClientServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientService");
                });

            modelBuilder.Entity("AML.Core.Entities.ServiceFieldMapping", b =>
                {
                    b.HasOne("AML.Core.Entities.ClientService", "ClientService")
                        .WithMany("FieldMappings")
                        .HasForeignKey("ClientServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientService");
                });

            modelBuilder.Entity("AML.Core.Entities.ServiceHeader", b =>
                {
                    b.HasOne("AML.Core.Entities.ClientService", "ClientService")
                        .WithMany("Headers")
                        .HasForeignKey("ClientServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientService");
                });

            modelBuilder.Entity("AML.Core.Entities.ServiceLog", b =>
                {
                    b.HasOne("AML.Core.Entities.ClientService", "ClientService")
                        .WithMany("Logs")
                        .HasForeignKey("ClientServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientService");
                });

            modelBuilder.Entity("AML.Core.Entities.Client", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("AML.Core.Entities.ClientService", b =>
                {
                    b.Navigation("Auth");

                    b.Navigation("Endpoint");

                    b.Navigation("FieldMappings");

                    b.Navigation("Headers");

                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
